import AppKit

struct ClipItem: Identifiable, Equatable {
    enum Payload: Equatable {
        case text(String)
        case file(URL)
        /// Several files copied at once. A multi-file copy used to be recorded
        /// as its first file alone, so pasting the entry back silently replaced
        /// the user's selection of twelve with one.
        case files([URL])
    }

    let id = UUID()
    let payload: Payload
    let date: Date
    /// Computed once at capture. `preview` used to trim the whole string on
    /// every render, for every row — twice, since the pane trimmed newlines out
    /// of the result — and a row is only ever a line high.
    let preview: String

    init(payload: Payload, date: Date) {
        self.payload = payload
        self.date = date
        self.preview = Self.preview(for: payload)
    }

    private static func preview(for payload: Payload) -> String {
        switch payload {
        case .text(let string):
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            let flattened = trimmed.replacingOccurrences(of: "\n", with: " ")
            return String(flattened.prefix(previewLimit))
        case .file(let url):
            return url.lastPathComponent
        case .files(let urls):
            guard let first = urls.first else { return "" }
            guard urls.count > 1 else { return first.lastPathComponent }
            return "\(first.lastPathComponent) + \(urls.count - 1)"
        }
    }

    /// A row shows one line; anything past this could never be read.
    static let previewLimit = 512

    var symbol: String {
        switch payload {
        case .text(let string):
            if string.hasPrefix("http://") || string.hasPrefix("https://") { return "link" }
            return "text.alignleft"
        case .file:
            return "doc"
        case .files:
            return "doc.on.doc"
        }
    }

    static func == (lhs: ClipItem, rhs: ClipItem) -> Bool { lhs.payload == rhs.payload }
}

/// Polls the general pasteboard's change counter. Cheap: one integer read
/// twice a second, and nothing at all is read until the counter moves.
@MainActor
final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [ClipItem] = []

    /// Raised for image data on the pasteboard — a screenshot taken straight to
    /// the clipboard, which would otherwise vanish after one paste.
    var onImage: ((Data) -> Void)?

    /// Whether images are worth reading at all. Asked before the TIFF → PNG
    /// encode, not after: with screenshot saving switched off, a copied picture
    /// would otherwise be encoded in full and then thrown away.
    var wantsImages: () -> Bool = { true }

    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int
    private let limit = 40
    /// Types an app sets to keep a copy out of history tools. Presence is what
    /// counts, not content: a type can be declared with data that is still on
    /// its way, and asking for the bytes would then answer nil for a password
    /// that is about to arrive. `ConcealedType` is what password managers set;
    /// the other two mark copies made by a machine rather than by a hand.
    private let optOut: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        stop()
        // Any copy made while the poll was stopped still counts: the counter is
        // compared against where it stood when the store was built, not
        // re-baselined here, so a pause for display sleep does not swallow the
        // copy that happened just before it.
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.pollNow() }
        }
        // The half-second is a ceiling, not a beat: nobody notices a copy
        // landing in history a fifth of a second late, and the slack lets the
        // system fold this wake-up into others.
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func clear() {
        items.removeAll()
    }

    func remove(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
    }

    /// Puts an entry back on the pasteboard without re-recording it.
    func copy(_ item: ClipItem) {
        pasteboard.clearContents()
        switch item.payload {
        case .text(let string):
            pasteboard.setString(string, forType: .string)
        case .file(let url):
            pasteboard.writeObjects([url as NSURL])
        case .files(let urls):
            pasteboard.writeObjects(urls.map { $0 as NSURL })
        }
        lastChangeCount = pasteboard.changeCount
        // Freshly used entries bubble to the top.
        if let index = items.firstIndex(where: { $0.id == item.id }), index != 0 {
            items.remove(at: index)
            items.insert(item, at: 0)
        }
    }

    func pollNow() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        guard pasteboard.availableType(from: optOut) == nil else { return }
        // Our own write — copying a screenshot back out of the shelf must not
        // save it to disk all over again.
        guard pasteboard.data(forType: .islaInternal) == nil else { return }

        // A copied file arrives as a URL, not as image data, so URLs win first.
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
           !urls.isEmpty {
            // All of them, not just the first: a Finder copy of a selection is
            // one copy, and pasting the history entry has to reproduce it.
            let payload: ClipItem.Payload = urls.count == 1 ? .file(urls[0]) : .files(urls)
            record(ClipItem(payload: payload, date: Date()))
            return
        }

        if wantsImages() {
            if pasteboard.availableType(from: [.png, .tiff]) != nil {
                encodeImage(at: pasteboard.changeCount)
                return
            }

        }

        guard let string = pasteboard.string(forType: .string),
              !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        record(ClipItem(payload: .text(Self.capped(string)), date: Date()))
    }

    /// Longest text kept per entry.
    ///
    /// The history was bounded by count alone, so forty copies of a log file
    /// pinned forty whole log files in memory for the rest of the session.
    /// Anything past this cannot be read in a one-line row or pasted back
    /// usefully from a scratch panel.
    static let maximumTextBytes = 256 * 1024

    private static func capped(_ string: String) -> String {
        guard string.utf8.count > maximumTextBytes else { return string }
        return String(decoding: Array(string.utf8.prefix(maximumTextBytes)), as: UTF8.self)
    }

    /// Reads the picture and, if it needs transcoding, does that off the main
    /// thread.
    ///
    /// A TIFF from the pasteboard is uncompressed — tens of megabytes for a
    /// Retina screen — and decoding it and re-encoding to PNG used to happen on
    /// the main actor, freezing the panel, the pointer sampler and every
    /// animation for as long as it took.
    ///
    /// A copy made on the phone arrives in two parts: macOS puts the type on
    /// the pasteboard the moment the phone announces it, and the picture itself
    /// is still coming over the air, so there may be nothing to read yet. That
    /// case waits.
    private func encodeImage(at changeCount: Int, attempt: Int = 0) {
        if let png = pasteboard.data(forType: .png) {
            deliverImage(png, at: changeCount)
            return
        }
        if let tiff = pasteboard.data(forType: .tiff) {
            DispatchQueue.global(qos: .userInitiated).async {
                let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
                DispatchQueue.main.async {
                    MainActor.assumeIsolated {
                        guard let png else {
                            // Undecodable image data. The copy may still have
                            // carried text, and dropping it outright lost that
                            // too — the change counter is already marked seen,
                            // so nothing would re-poll it.
                            self.recordTextFallback(at: changeCount)
                            return
                        }
                        self.deliverImage(png, at: changeCount)
                    }
                }
            }
            return
        }

        // Nothing readable yet. Give up after a few seconds and fall back to
        // whatever else the copy carried, so a copy that merely offered an
        // image alongside its text is still recorded.
        guard attempt < 12 else {
            recordTextFallback(at: changeCount)
            return
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
            MainActor.assumeIsolated {
                guard let self else { return }
                guard self.pasteboard.changeCount == changeCount else { return }
                // Image saving can be switched off while a picture is still in
                // flight. The copy is still worth recording — dropping it
                // outright lost the text it came with too, and the change
                // counter was already marked seen so nothing would re-poll it.
                guard self.wantsImages() else {
                    self.recordTextFallback(at: changeCount)
                    return
                }
                self.encodeImage(at: changeCount, attempt: attempt + 1)
            }
        }
    }

    private func deliverImage(_ png: Data, at changeCount: Int) {
        // The pasteboard may have moved on while the encode was running, and a
        // newer copy is the newer intention.
        guard pasteboard.changeCount == changeCount else { return }
        guard wantsImages() else {
            recordTextFallback(at: changeCount)
            return
        }
        onImage?(png)
    }

    private func recordTextFallback(at changeCount: Int) {
        guard pasteboard.changeCount == changeCount,
              let string = pasteboard.string(forType: .string),
              !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        // Capped like every other text capture: this path used to be the one
        // way an unbounded string still reached the history.
        record(ClipItem(payload: .text(Self.capped(string)), date: Date()))
    }

    private func record(_ item: ClipItem) {
        items.removeAll { $0 == item }
        items.insert(item, at: 0)
        if items.count > limit { items.removeLast(items.count - limit) }
    }
}
